[pytest]
filterwarnings =
    ignore:The 'is_flag' and 'flag_value' parameters are not supported by Typer:DeprecationWarning
    ignore:`huggingface_hub` cache-system uses symlinks by default:UserWarning