export type Defense = {
   id: string;
   name: string;
   description: string;
   longDescription: string;
   references: string[];
};

const defenses: Defense[] = [
   {
      id: "None",
      name: "None",
      description: "No defense.",
      longDescription:
         "No mitigation is applied. This setting serves as a baseline control group to measure the raw effectiveness of attack vectors against the unprotected model. It exposes the system to all forms of prompt injection, jailbreaking, and leakage, providing a clear 'before' picture to contrast with 'after' results when defenses are enabled.\n\nIn an experimental setting, the 'None' configuration is essential: it allows practitioners to quantify how much each individual defense or combination of defenses actually improves robustness. By comparing attack success rates, response quality, and safety violations under 'None' versus protected modes, teams can identify which mitigations offer the best trade-off between security, latency, and user experience.",
      references: [],
   },
   {
      id: "input_sanitization",
      name: "Input Sanitization",
      description:
         "Filters and sanitizes user inputs to detect and block malicious patterns before processing.",
      longDescription:
         "Input sanitization is the first line of defense, operating before the prompt ever reaches the LLM. It involves analyzing the user's text for known malicious patterns, keywords, or structural anomalies.\n\nTechniques include:\n• **Signature-based detection:** Blocking known jailbreak phrases (e.g., 'Ignore all previous instructions').\n• **Perplexity filtering:** Detecting gibberish or adversarial suffixes that have unusually high or low statistical likelihood.\n• **LLM-based pre-checks:** Using a smaller, faster model to classify the intent of the incoming prompt as 'safe' or 'unsafe'.\n\nWhile effective against script kiddies and known attacks, it can often be bypassed by novel obfuscation or semantic variations. For this reason, input sanitization is usually combined with additional layers such as output filtering and contextual policies. Careful tuning is required: overly aggressive sanitization can frustrate legitimate users or block harmless edge cases, while overly permissive rules may let sophisticated attacks slip through.",
      references: [
         "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html - OWASP Input Validation Cheat Sheet",
         "https://arxiv.org/abs/2308.07309 - 'Certifying LLM Safety against Adversarial Prompting'",
      ],
   },
   {
      id: "output_filtering",
      name: "Output Filtering",
      description:
         "Monitors and filters model outputs to prevent harmful or inappropriate content from being returned.",
      longDescription:
         "Output filtering acts as a safety net, inspecting the content generated by the model before it is shown to the user. Even if a malicious prompt bypasses input defenses, output filtering can catch the harmful result.\n\nThis often involves:\n• **Keyword blocking:** preventing the display of specific sensitive words.\n• **Toxicity classifiers:** running the output through a separate model trained to detect hate speech, violence, or sexual content.\n• **Refusal enforcement:** ensuring that if the model starts to generate a refusal (e.g., 'I cannot assist with...'), it is not subsequently tricked into answering anyway.\n\nIn practice, advanced systems go beyond simple word lists, using contextual classifiers and fine-grained policies (e.g., allowing high-level medical discussion but blocking step-by-step self‑harm instructions). Output filtering is a critical layer for defense‑in‑depth but adds latency and infrastructure complexity, so teams must balance security needs with responsiveness and cost.",
      references: [
         "https://openai.com/safety - OpenAI Safety Overview",
         "https://arxiv.org/abs/2306.12685 - 'Safety-Tuned LLaMA: Lessons From Improving the Safety of Large Language Models'",
      ],
   },
   {
      id: "rate-limiting",
      name: "Rate Limiting",
      description:
         "Restricts the number of requests to prevent abuse and automated attacks.",
      longDescription:
         "Rate limiting is an infrastructure-level defense that restricts the frequency of requests from a single user or IP address. While it doesn't stop a single well-crafted attack, it is highly effective against automated, iterative attacks like 'Bias Guided FCB' or 'Gradient-based Optimization'.\n\nThese advanced attacks often require thousands of queries to 'probe' the model and find a weakness. By enforcing strict rate limits (e.g., 5 requests per minute), the cost and time required to mount such an attack become prohibitive, effectively neutralizing the threat of automated jailbreaking tools.\n\nBeyond pure security, rate limiting also protects system reliability and availability by preventing accidental or malicious denial-of-service scenarios. When combined with identity, billing, and anomaly-detection signals, it becomes part of a broader abuse‑prevention strategy for real-world LLM applications.",
      references: [
         "https://cloud.google.com/armor/docs/rate-limiting-overview - Google Cloud Armor rate limiting overview",
         "https://www.cloudflare.com/learning/bots/what-is-rate-limiting/ - Cloudflare: What is rate limiting?",
      ],
   },
   {
      id: "context-isolation",
      name: "Context Isolation",
      description:
         "Separates system prompts from user inputs to prevent prompt injection attacks.",
      longDescription:
         "Context Isolation (often called 'Prompt Sandboxing' or 'XML Tagging') aims to structurally separate the developer's system instructions from the untrusted user input. Instead of concatenating them into a single string, the system uses special tokens or formatting to delineate boundaries.\n\nFor example, wrapping user input in `<user_input>` tags and instructing the model to 'only process text inside these tags and ignore instructions within them'. This helps the model distinguish between *data* to be processed and *code* (instructions) to be executed, mitigating the risk of the model confusing a user's 'Ignore previous instructions' command with a legitimate system directive.\n\nIn modern tool-using agents and retrieval-augmented systems, context isolation can also involve separating retrieved documents, tool outputs, and policy text into distinct channels. Properly designed, this reduces cross-contamination between trusted and untrusted sources and makes it easier to audit which part of the context led to a particular response.",
      references: [
         "https://learn.microsoft.com/azure/ai-services/openai/concepts/advanced-prompt-engineering - Microsoft: Advanced prompt engineering",
         "https://simonwillison.net/2023/May/2/prompt-injection-explained/ - Simon Willison: Prompt injection explained",
      ],
   },
   {
      id: "masked_defender",
      name: "MaskedDefender",
      description:
         "A neural network-based defense mechanism against LLM jailbreak attacks",
      longDescription:
         "MaskedDefender is a specialized, learned defense mechanism designed to counter sophisticated jailbreak attacks. It operates by identifying and 'masking' (hiding or redacting) the specific parts of a prompt that contribute to its malicious nature, while preserving the benign context.\n\nIt typically uses a trained BERT-based or similar encoder model to score the 'harmfulness' of each token in the input. High-risk tokens are replaced with a mask token (e.g., `[MASK]`), rendering the adversarial instruction unintelligible to the target LLM. This approach is more robust than simple keyword filtering because it learns the *context* of harmfulness rather than just a list of bad words.\n\nIn practice, MaskedDefender can be tuned to operate at different sensitivity thresholds, trading off false positives (over-masking harmless content) against false negatives (failing to mask subtle attacks). When combined with other defenses such as rate limiting and output filtering, it contributes to a layered security architecture that targets both simple and highly optimized jailbreak attempts.",
      references: [
         "https://arxiv.org/abs/2402.08707 - Example paper on masking-based defenses for LLMs",
         "./MaskedDefender/README.md - Local project documentation for MaskedDefender",
      ],
   },
];

export default defenses;
