apiVersion: v1
kind: Service
metadata:
   name: backend
spec:
   selector:
      app: backend
   ports:
      - port: 8000
        targetPort: 8000
   type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: backend
spec:
   replicas: 1
   selector:
      matchLabels:
         app: backend
   template:
      metadata:
         labels:
            app: backend
      spec:
         nodeSelector:
            accelerator: nvidia-l4
         tolerations:
            - key: "nvidia.com/gpu"
              operator: "Equal"
              value: "present"
              effect: "NoSchedule"
         containers:
            - name: backend
              image: europe-central2-docker.pkg.dev/nomadic-memento-476510-h5/projektr/backend:latest
              ports:
                 - containerPort: 8000
              env:
                 - name: REDIS_URL
                   value: "redis://redis:6379/0"
              resources:
                 limits:
                    nvidia.com/gpu: 1
